name: Scala Course CI

on:
  push:
    branches: [ exercises-master ]
  pull_request:
    branches: [ exercises-master ]

jobs:
#   test_course:
#     runs-on: ubuntu-latest

#     steps:

#       - name: Checkout Course Repo
#         uses: actions/checkout@v2
#         with:
#           path: course-master
#           fetch-depth: 0
        
#       - name: Checkout Course Management Tools
#         uses: actions/checkout@v2
#         with:
#           repository: lightbend/course-management-tools
#           path: CMT
      
#       - name: Set up JDK 11
#         uses: actions/setup-java@v1
#         with:
#           java-version: 11
      
#       - name: Cache Ivy and SBT
#         uses: actions/cache@v2
#         with:
#           path: | 
#             ~/.ivy2/cache
#             ~/.sbt            
#           key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('project/**') }}
#           restore-keys: |
#             ${{ runner.os }}-sbt-ivy-cache-
#             ${{ runner.os }}-
      
#       - name: Generate Tests Script using CMT
#         run: |
#           (cd CMT/ && exec sbt "masteradm -dot -t ../runTests $GITHUB_WORKSPACE/course-master")
     
#       - name: Run Tests
#         run: |
#           chmod +x runTests
#           ./runTests
          
  create_release:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout Course Management Tools
        uses: actions/checkout@v2
        with:
          repository: lightbend/course-management-tools
          path: CMT
          
      - name: Checkout Course Repo
        uses: actions/checkout@v2
        with:
          path: lunatech-scala-2-to-scala3-course
          fetch-depth: 0          
      
      - name:  List directory
        run: |
          ls -l
          echo "PWD: $(pwd)"
#       - name: Set up JDK 11
#         uses: actions/setup-java@v1
#         with:
#           java-version: 11
      
#       - name: Cache Ivy and SBT
#         uses: actions/cache@v2
#         with:
#           path: | 
#             ~/.ivy2/cache
#             ~/.sbt            
#           key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('project/**') }}
#           restore-keys: |
#             ${{ runner.os }}-sbt-ivy-cache-
#             ${{ runner.os }}-
      
#       - name: Studentify Repo
#         run: |
#           (cd CMT/ && exec sbt "studentify -dot -t $GITHUB_WORKSPACE/course-master")
