name: Scala Course CI

on:
  push:
    branches: [ exercises-master ]
  pull_request:
    branches: [ exercises-master ]

jobs:
  test_course:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Course Repo
        uses: actions/checkout@v2
        with:
          path: course-master
          fetch-depth: 0
          
      - name: Cache Course Management Tools repo
        uses: actions/cache@v2
        id: cache_cmt
        with:
          path: $GITHUB_WORSPACE/CMT
          key: ${{ runner.os }}-cmt-cache-${{ hashFiles('project/**') }}
          restore-keys: |
            ${{ runner.os }}-cmt-cache-
            ${{ runner.os }}-
        
      - name: Checkout Course Management Tools
        # Checkout CMT only if not present in cache
        if: steps.cache_cmt.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: lightbend/course-management-tools
          path: CMT
      
#       - name: Set up JDK 11
#         uses: actions/setup-java@v1
#         with:
#           java-version: 11
      
#       - name: Cache Ivy and SBT
#         uses: actions/cache@v2
#         with:
#           path: | 
#             ~/.ivy2/cache
#             ~/.sbt            
#           key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('project/**') }}
#           restore-keys: |
#             ${{ runner.os }}-sbt-ivy-cache-
#             ${{ runner.os }}-
      
#       - name: Generate Tests Script using CMT
#         run: |
#           (cd CMT/ && exec sbt "masteradm -dot -t ../runTests $GITHUB_WORKSPACE/course-master")
#           cat runTests
          
#       - name: List workspace contents
#         run: |
#           ls -l
#           echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
#           echo "PWD: $(pwd)"
     
#       - name: Run Tests
#         run: |
#           chmod +x runTests
#           ./runTests
          
