name: Scala Course CI

on:
  push:
    branches: [ ci-setup ]
  pull_request:
    branches: [ ci-setup ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Course Management Tools
        uses: actions/checkout@v2
        with:
          repository: lightbend/course-management-tools
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      #- name: Run tests
      #  run: sbt test
